[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "client"
version = "0.1.0"
description = "Data Fabric Client"
requires_python = ">=3.10"
license = { text = "Apache-2.0" }

packages = ["client"]

authors = [
    { name = "Stephan Trattnig", email = "stephan.trattnig@iwb.tum.de" }
]
